site_name: personal-知识库
site_description: 分享软件开发经验与技术心得的个人博客
site_author: AI之覔
copyright: Copyright © AI之覔
repo_url: https://github.com/serendipitywgy/personal-docs

nav:
  - 开发工具: 
    - cmake:
      - 开发工具/cmake/00-知识碎碎念.md
      - 开发工具/cmake/01-安装与基本介绍.md
      - 开发工具/cmake/02-CMake 的文件分布.md
      - 开发工具/cmake/03-变量的设置与引用.md
      - 开发工具/cmake/04-运算符与条件、循环语句.md
      - 开发工具/cmake/05-目标构建.md
      - 开发工具/cmake/06-变量参与 C++ 的编译.md
      - 开发工具/cmake/07-宏与函数.md
      - 开发工具/cmake/08-find_package 详解.md
      - 开发工具/cmake/09-生成器表达式.md
      - 开发工具/cmake/10-项目的导出与安装.md
      - 开发工具/cmake/11-项目实战.md
      - 开发工具/cmake/12-CTest 工具.md
      - 开发工具/cmake/13-CPack 工具.md
  - C++:
    - C++进阶:
      - C++/C++进阶/01-C++的内存结构.md
      - 02-C++模板:
        - C++/C++进阶/02-C++模板/01-模板-基本概念.md
        - C++/C++进阶/02-C++模板/02-模板-类模板.md
        - C++/C++进阶/02-C++模板/03-模板-函数模板.md
      - 03-STL标准模板库:
        - C++/C++进阶/03-STL标准模板库/01-STL.md
        - C++/C++进阶/03-STL标准模板库/02-什么是容器.md
        - C++/C++进阶/03-STL标准模板库/03-vector容器.md
        - C++/C++进阶/03-STL标准模板库/05-迭代器.md
        - C++/C++进阶/03-STL标准模板库/06-deque（双端队列）.md
        - C++/C++进阶/03-STL标准模板库/07-list.md
        - C++/C++进阶/03-STL标准模板库/08-Map容器.md
        - C++/C++进阶/03-STL标准模板库/09-Set容器.md
        - C++/C++进阶/03-STL标准模板库/10-stack容器.md
        - C++/C++进阶/03-STL标准模板库/11-queque.md
        - C++/C++进阶/03-STL标准模板库/12-unordered_map 和 unordered_set.md
        - C++/C++进阶/03-STL标准模板库/13-仿函数（函数对象）.md
        - C++/C++进阶/03-STL标准模板库/14-算法.md
        - C++/C++进阶/03-STL标准模板库/15-内存分配器.md
        - C++/C++进阶/03-STL标准模板库/16-函数适配器.md
      - 04-文件流操作:
        - C++/C++进阶/04-文件流操作/文件流操作.md
      - 05-多线程编程:
        - C++/C++进阶/05-多线程编程/01-多线程基础.md
        - C++/C++进阶/05-多线程编程/02-创建多线程.md
        - C++/C++进阶/05-多线程编程/03-线程同步与mutex.md
        - C++/C++进阶/05-多线程编程/04-lock_guard.md
        - C++/C++进阶/05-多线程编程/05-unique_lock.md
        - C++/C++进阶/05-多线程编程/06-线程间同步方式.md
        - C++/C++进阶/05-多线程编程/07-条件变量condition_variable.md
        - C++/C++进阶/05-多线程编程/08-读写锁.md
        - C++/C++进阶/05-多线程编程/09-原子变量和原子操作.md
        - C++/C++进阶/05-多线程编程/10-信号量和counting_semaphore.md
        - C++/C++进阶/05-多线程编程/11-栅栏（barrier）.md
        - C++/C++进阶/05-多线程编程/12-死锁.md
        - C++/C++进阶/05-多线程编程/13-异步编程 future和async.md
        - C++/C++进阶/05-多线程编程/14-异步编程 promise的用法.md
        - C++/C++进阶/05-多线程编程/15-异步编程 packaged_task的使用.md
        - C++/C++进阶/05-多线程编程/16-三种异步工具的比较.md
        - C++/C++进阶/05-多线程编程/17-线程池.md
        - C++/C++进阶/05-多线程编程/18-多线程小结.md
      - 06-网络编程:
        - C++/C++进阶/06-网络编程/01-网络基础-协议和分层.md
        - C++/C++进阶/06-网络编程/02-网络基础-TCPIP四层模型、MAC和IP.md
        - C++/C++进阶/06-网络编程/03-ARP协议与主机之间的通信.md
        - C++/C++进阶/06-网络编程/04-TCP协议和包头解析.md
        - C++/C++进阶/06-网络编程/05-TCP的三次握手和四次挥手.md
        - C++/C++进阶/06-网络编程/06-字节序 大端和小端.md
        - C++/C++进阶/06-网络编程/07-socket编程 和 TCP协议.md
        - C++/C++进阶/06-网络编程/08-UDP协议 和 Socket编程.md
        - C++/C++进阶/06-网络编程/09-IP，单播、广播、组播、任播.md
        - C++/C++进阶/06-网络编程/10-http.md
  - opencv4:
      - opencv4/01-OpenCV4概述.md

  - 爱情树: love-tree/index.html  # 添加这一行
            


  #   - linux系统:
  #   - 构建工具:
  # - 随笔感悟:
  - GitHub: https://github.com/serendipitywgy/personal-docs

plugins:
  - search
  # - macros
  # - print-site
theme:
  name: material
  language: zh
  palette:
    # 可切换亮色/暗色模式
    - media: "(prefers-color-scheme: light)"  
      scheme: default
      primary: teal
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: 切换至深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: teal
      toggle:
        icon: material/brightness-4
        name: 切换至浅色模式
  
  features:
    - navigation.tabs # 顶部显示导航标签
    - navigation.sections # 导航节
    - navigation.expand # 导航展开
    - navigation.top # 返回顶部按钮
    - search.suggest # 搜索建议
    - search.highlight # 搜索高亮
    - content.tabs.link # 内容标签
    - content.code.copy # 代码复制按钮
    - content.code.annotate # 代码注释

  font:
    text: Roboto, "Noto Sans SC"
    code: "JetBrains Mono"
# 代码高亮
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  
# 额外的CSS自定义
extra_css:
  - stylesheets/extra.css

# 额外的JS
extra_javascript:
  - javascripts/extra.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

  # 添加这个部分
extra_templates:
  - love-tree/index.html
  - love-tree/tree.html
# 页脚社交链接
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/serendipitywgy/personal-doc
