site_name: personal-知识库
site_description: 分享软件开发经验与技术心得的个人博客
site_author: AI之覔
copyright: Copyright © AI之覔
repo_url: https://github.com/serendipitywgy/personal-docs

nav:
  - 首页: index.md
  - 技术博文:
    - 开发工具: 
      - cmake:
        - 开发工具/cmake/01-安装与基本介绍.md
        - 开发工具/cmake/02-CMake 的文件分布.md
        - 开发工具/cmake/03-变量的设置与引用.md
        - 开发工具/cmake/04-运算符与条件、循环语句.md
        - 开发工具/cmake/05-目标构建.md
        - 开发工具/cmake/06-变量参与 C++ 的编译.md
        - 开发工具/cmake/07-宏与函数.md
        - 开发工具/cmake/08-find_package 详解.md
        - 开发工具/cmake/09-生成器表达式.md
        - 开发工具/cmake/10-项目的导出与安装.md
        - 开发工具/cmake/11-项目实战.md
        - 开发工具/cmake/12-CTest 工具.md
        - 开发工具/cmake/13-CPack 工具.md
    - C++:
      - C++进阶:
        - C++/C++进阶/01-C++的内存结构.md
        - 02-C++模板:
          - C++/C++进阶/02-C++模板/01-模板-基本概念.md
          - C++/C++进阶/02-C++模板/02-模板-类模板.md
          - C++/C++进阶/02-C++模板/03-模板-函数模板.md
        - 03-STL标准模板库:
          - C++/C++进阶/03-STL标准模板库/01-STL.md
          - C++/C++进阶/03-STL标准模板库/02-什么是容器.md
          - C++/C++进阶/03-STL标准模板库/03-vector容器.md
          - C++/C++进阶/03-STL标准模板库/05-迭代器.md
          - C++/C++进阶/03-STL标准模板库/06-queque.md
          - C++/C++进阶/03-STL标准模板库/07-list.md
          - C++/C++进阶/03-STL标准模板库/08-Map容器.md
          - C++/C++进阶/03-STL标准模板库/09-Set容器.md
          - C++/C++进阶/03-STL标准模板库/10-stack容器.md
          - C++/C++进阶/03-STL标准模板库/11-deque（双端队列）.md
          - C++/C++进阶/03-STL标准模板库/12-unordered_map 和 unordered_set.md
          - C++/C++进阶/03-STL标准模板库/13-仿函数（函数对象）.md
          - C++/C++进阶/03-STL标准模板库/14-算法.md
          - C++/C++进阶/03-STL标准模板库/16-函数适配器.md
            


  #   - linux系统:
  #   - 构建工具:
  # - 随笔感悟:
  - GitHub: https://github.com/serendipitywgy/personal-docs

plugins:
  - search
  # - macros
  # - print-site
theme:
  name: material
  language: zh
  palette:
    # 可切换亮色/暗色模式
    - media: "(prefers-color-scheme: light)"  
      scheme: default
      primary: teal
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: 切换至深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: teal
      toggle:
        icon: material/brightness-4
        name: 切换至浅色模式
  
  features:
    - navigation.tabs # 顶部显示导航标签
    - navigation.sections # 导航节
    - navigation.expand # 导航展开
    - navigation.top # 返回顶部按钮
    - search.suggest # 搜索建议
    - search.highlight # 搜索高亮
    - content.tabs.link # 内容标签
    - content.code.copy # 代码复制按钮
    - content.code.annotate # 代码注释

  font:
    text: Roboto, "Noto Sans SC"
    code: "JetBrains Mono"
# 代码高亮
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  
# 额外的CSS自定义
extra_css:
  - stylesheets/extra.css

# 额外的JS
extra_javascript:
  - javascripts/extra.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# 页脚社交链接
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/serendipitywgy/personal-doc
